#!/usr/bin/env bash
set -eu

echo "# Books"
echo "Some books organised by topic."
echo

last=""
find . -type f -name "*.pdf"|sort|while read path
do
  dir=$(dirname "${path}")
  if [[ $dir != $last ]]
  then
    name=${dir:2}
    first=$(echo ${name:0:1}|tr a-z A-Z)
    rest=$(echo ${name:1})
    echo
    echo "### ${first}${rest//\// / }"
    echo
    last=$dir
  fi
  name=${path}
  title="${name//$dir\//}"
  len="${#title}"
  max="$(( $len - 4))"
  link="${path:2}"
  link="${link// /%20}"

  echo "- [${title:0:$max}]($link)"
done
