#!/usr/bin/env bash
set -eu

echo "# Books"
echo "Some books uploaded organised by topic"
echo

last=""
find . -type f -name "*.pdf"|sort|while read path
do
  dir=$(dirname "${path}")
  if [[ $dir != $last ]]
  then
    echo
    first=$(echo ${dir:2:3}|tr a-z A-Z)
    rest=$(echo ${dir:3})
    # echo $title
    echo "## ${first}${rest}"
    echo
    last=$dir
  fi
  name=${path}
  echo "- ${name//$dir\//}"
done
